### ISSUE TITLE
Add support for chriso's validator (chriso/validator.js)

### ISSUE THREAD

**Issue by RWOverdijk** [aurelia/validation#1]
## Introduction
Validating webforms, response data and other forms of information is a common task. Therefor, I believe it's important to make sure it's easy to do and doesn't cause any performance issues.

## NIH?
I'm not sure what Aurelia's policy is on this, but I personal prefer using existing libraries which have proven themselves over time.

A great example of this is chriso's validator ([chriso/validator.js](https://github.com/chriso/validator.js)). It has built-in string validators and works really well. Sails.js uses it in Anchor ([balderdashy/anchor](https://github.com/balderdashy/anchor)) with added object validation and more.

## In comes Aurelia
I'm again not quite sure how Aurelia would like to use this. I think that supplying a common format of using the validator is the way to go. We could then bind objects to the validator, and have them validate when asked.

I have two ideas on how to do this.

### Validated entities
We could create the concept of "validated entities". An entity is simply a class with defined rules (properties and their validation and filtering). These entities will be used to construct objects of data, validate the data they hold and return filtered data. This could be useful for validating and filtering responses from API calls, as well as validating and filtering data that is to be sent to an API. An example:

```javascript
class AbstractEntity {
  validate () { }

  isValid () { }

  getErrors () { }

  setData () { }

  getData (raw) { }
}

export default class UserEntity extends AbstractEntity {
  construct () {
    this.rules = {
      username : {
        type    : 'string',
        required: true,
        regex   : /^[\w\-]{2,14}$/
      },
      password : {
        type : 'string',
        required: true,
      }
    };
  }
}
```

### Library
The other method requires less work, and simply offers validation as an import. The developer uses the library the way he or she wants to without having to follow any conventions.

## What do you think?
This is just a quick proposal I wanted to post to start a conversation.

**Comment by EisenbergEffect** [comment]
@janvanderhaegen has a first pass implementation of a validation library. @janvanderhaegen any idea when you are going to be able to push your code here?

**Comment by RWOverdijk** [comment]
@EisenbergEffect I know, but this is his own implementation. I don't think that's the best approach, seeing how there's already an amazing lib out there we could use..

**Comment by EisenbergEffect** [comment]
@RWOverdijk  Do you have a demo that uses this library? I'd like to see it up and running with Aurelia and a UI that reflects the validation. That will allow us to compare the two.

**Comment by RWOverdijk** [comment]
@EisenbergEffect Besides it having 3,307 stars of github, no. I haven't used it with Aurelia yet. But like I said in the description of the issue, it is being used for sails. Just check out [the examples](https://github.com/chriso/validator.js#validators). We can still use a repo like this one to slightly alter the way you use it. I just don't think we should write all those validation rules _again_ because these have been tested and have matured.

I am not affiliated with the lib in any way. I've just used it, and know it's solid. Could be a time saver, too...

**Comment by EisenbergEffect** [comment]
Ok, well we probably still need @janvanderhaegen to write the plugin, but he could leverage the rules engine from this library. That sounds pretty reasonable. Perhaps we can make it pluggable with this library as the default validation engine even? @janvanderhaegen Can you look into that?

**Comment by RWOverdijk** [comment]
@EisenbergEffect That sounds good.

**Comment by janvanderhaegen** [comment]
Hey @EisenbergEffect @RWOverdijk ,

RE: chrisco/validator: that library is amazing and has been on my radar for a while (I actually use it as a reference quite often, as well as some other ones like the knockout.validation plugin too).
It would be foolish to ignore the massive value of these validation rules, but we also need to recognize that this library is just (string) validation rules, ie we still need:
- UI integration
- UX / feedback (you only get a true or false)
- conditional validation
- complex validation (nested objects, arrays of objects, etc)
- non-string validation (arrays, numbers, etc)
- value-changed-triggers (this library's validation is to be called 'on-demand')
Hence, I'd like to move forward with @EisenbergEffect 's idea of keeping the existing integration plugin but making sure we can plug this library in as a validation-rules engine.  The question thus becomes if we use this as the default rules engine or not. Personally I'm more in favor of keeping the existing non-dependency approach, but also writing a plugin so that the many validation rules of this library can be effortlessly plugged in?

RE: API: I think the API we currently have is very similar in concept to the AbstractEntity you describe.
```javascript
  this.validation = validation.on(this)
    .ensure('firstName').notEmtpy().matches( /^[\w\-]{2,14}$/)
    .ensure('password').notEmpty().strongPassword();
```
The result of this snippet is that there's now a 'validation' property (composition, not inheritance) that has your 'validate', 'isValid' and 'getErrors' methods ready to go. The 'on(this)' part pretty much matches your 'setData' functionality, only we bind to the entity instead of setting the data. The part that we miss but I don't conceptually understand yet is the 'getData(raw)'

@EisenbergEffect I'm a bit slammed in real life atm, working on the nested properties (using that binding trick) and splitting up the documentation. Everything will be cleaned up and moved here by Monday though!!

**Comment by EisenbergEffect** [comment]
@janvanderhaegen Sounds good.

**Comment by samirbr** [comment]
Hey @EisenbergEffect @RWOverdijk,

One approach I find intetesting is add validators decorators to the class properties.

@validator({
        type    : 'string',
        required: true,
        regex   : /^[\w\-]{2,14}$/
      })
username

**Comment by janvanderhaegen** [comment]
@samirbr This is definitely on our short-list! https://github.com/aurelia/validation/issues/36

**Comment by janvanderhaegen** [comment]
@samirbr This will now be included in the next release https://github.com/aurelia/validation/blob/master/doc/Intro.md#the-ensure-decorator

**Comment by PWKad** [comment]
I'm closing this out for now - we appreciate the idea but doesn't seem like it's gained any traction and validation is well used now.
