### ISSUE TITLE
Build / distributed package

### ISSUE THREAD

**Issue by jods4** [aurelia/validation#102]
Over the last few months, almost all of Aurelia packages have changed their distribution format (for the better). Instead of `index.js` and a lots of small packages files around, they are now mostly built out of a single `aurelia-XYZ.js` file.

`aurelia-validation` is still distributed as a bunch of packaged file, which complicates bundling. Also, I think the change of format was done because it improved loading time slightly.

One think that is a bit unique here is the distribution of locales. I suggest that one locale is automatically bundled with the lib (`en-us`) so that the library _just works_ for the unaware dev (I was bitten by this). Then it should be easy for devs to additionally bundle the locales they want/need.

A final point is that other aurelia modules now automatically build and distribute a Typescript definition, which is sorely missing here.

**Comment by PWKad** [comment]
Tracking plan in #129

**Comment by PWKad** [comment]
Thanks for submitting this / commenting on this.  At this time we are closing this because we have completely re-written and are deprecating the previous feature set.  If you feel this should be re-opened please feel free to review [this blog post](http://blog.durandal.io/2016/05/03/aurelias-new-validation-and-testing-capabilities/) and submit either again on this repository, or on the new [validatejs bridge repository](https://github.com/aurelia/validatejs)

Thanks again!
