### ISSUE TITLE
can't validate multiple members of an object when composed

### ISSUE THREAD

**Issue by mbroadst** [aurelia/validation#116]
I've been writing my own validation strategy, and discovered that `updateElement` and `prepareElement` are initially called for both of the following properties, but no subsequent `updateElement` is called for the second property:

```
import {inject} from 'aurelia-framework';
import {Validation} from 'aurelia-validation';

@inject(Validation)
export class Test {
  record = {}
  constructor(validation) {
    this.validation = validation.on(this)
      .ensure('record.blah')
            .isNotEmpty()
            .hasMinLength(3)
            .hasMaxLength(10)
      .ensure('record.halb')
            .isNotEmpty()
            .hasMinLength(3)
            .hasMaxLength(10);
  }
}
```

**Comment by mbroadst** [comment]
any ideas on what's going on here?

**Comment by mbroadst** [comment]
Okay this was initially improperly named, because you:
   * already have a test for nested values
   * that totally works

My particular case is a little bit more involved. I've got a "dialog fragment" which I am composing in a top level dialog, which conveys data through the fragments `activate` method. When the bound object comes in that way, validation only works on the first nested reference to the data.

Here is a plunker that shows this behavior: http://plnkr.co/edit/HS0SurEzHDoxyseplx08

**Comment by mbroadst** [comment]
It looks like the issue is because the dialog-fragment doesn't have a default assignment for `record` when its created (it was only being set by the params passed into `activate`). If you add `record = {}` after `export class DialogFragment {` in `dialog-fragment.js` I get the update events

**Comment by PWKad** [comment]
Thanks for submitting this / commenting on this.  At this time we are closing this because we have completely re-written and are deprecating the previous feature set.  If you feel this should be re-opened please feel free to review [this blog post](http://blog.durandal.io/2016/05/03/aurelias-new-validation-and-testing-capabilities/) and submit either again on this repository, or on the new [validatejs bridge repository](https://github.com/aurelia/validatejs)

Thanks again!
