### ISSUE TITLE
Bug? I can enter spaces as first characters when using .canBeEmpty().containsNoSpaces()

### ISSUE THREAD

**Issue by valichek** [aurelia/validation#120]
When I start with entering spaces it validates to __true__ until I enter "not space" char.
```javascript
validation.on(target).ensure('contact.password').canBeEmpty().containsNoSpaces()
```

**Comment by janvanderhaegen** [comment]
The isNotEmpty (or the inverse: canBeEmpty) is evaluated before any other rule. 
[However we do trim strings ](https://github.com/aurelia/validation/blob/master/src/validation/utilities.js#L21) before evaluating if they are an 'empty' value, so your '     ' is considered empty and thus valid, until you type a non-space char and it starts evaluating the other rules (containsNoSpaces).

Not sure how we can change this without breaking the api,
```
ensure('firstname').isNotEmpty().hasMaxLength(3)
```
This would consider '  ' to be valid, although it's really not what you want the user to be able to enter as a first name.

We could add overloads isNotEmptyOrWhitespace and canBeEmptyOrWhitespace...

OTOH I can assume many people will prefer 'isNotEmpty()' to check for isNotEmptyOrWhitespace by default.

Thoughts?

**Comment by PWKad** [comment]
Thanks for submitting this / commenting on this.  At this time we are closing this because we have completely re-written and are deprecating the previous feature set.  If you feel this should be re-opened please feel free to review [this blog post](http://blog.durandal.io/2016/05/03/aurelias-new-validation-and-testing-capabilities/) and submit either again on this repository, or on the new [validatejs bridge repository](https://github.com/aurelia/validatejs)

Thanks again!
