### ISSUE TITLE
Consider json-schema

### ISSUE THREAD

**Issue by EisenbergEffect** [aurelia/validation#13]
It would be interested if we could build up a validation configuration based on json-schema. http://json-schema.org/ This is a lower priority than other issues. Just putting it here for a possible future addition.

**Comment by heruan** [comment]
:+1: 
Something like this would be awesome `this.validation = validation.on(this).schema(jsonSchema)`.

**Comment by RWOverdijk** [comment]
I'd love this. I currently write validations for backend and frontend.

**Comment by ariovistus** [comment]
I have done something similar on a recent project to automatically pull server side validation from @jeremyskinner's FluentValidation into aurelia-validation, and found myself wondering if there is a standard schema somewhere. And then I thought what if you had something analogous to swagger spec, but just to describe api validations that could also be performed on client side. But anyways, some random things that occurred to me while I was working on it:

- defining the order of your validations matters
- I still want to be able to specify validations clientside manually for more complicated scenarios.

eh, tl;dr this idea is cool, I want it too.

**Comment by PWKad** [comment]
Thanks for submitting this / commenting on this.  At this time we are closing this because we have completely re-written and are deprecating the previous feature set.  If you feel this should be re-opened please feel free to review [this blog post](http://blog.durandal.io/2016/05/03/aurelias-new-validation-and-testing-capabilities/) and submit either again on this repository, or on the new [validatejs bridge repository](https://github.com/aurelia/validatejs)

Thanks again!
