### ISSUE TITLE
d.ts Generation

### ISSUE THREAD

**Issue by EisenbergEffect** [aurelia/validation#133]
Configure the build to use the d.ts generator plugin to ensure that proper d.ts files are built from the source. In combination with this, set up the new documentation infrastructure which will generate correct API docs from the d.ts file as well as use the TypeScript compiler to validate that the d.ts is correct. You can see how this is done by looking at the build and doc tasks in any of the core repos.

**Comment by PWKad** [comment]
The d.ts is being generated now by https://github.com/aurelia/validation/pull/141 but still need to wire up the docs.

**Comment by PWKad** [comment]
API.json generated in https://github.com/aurelia/validation/pull/145

**Comment by mikeobrien** [comment]
Looks like [the view strategies are missing from the d.ts file](https://github.com/aurelia/validation/blob/master/dist/es6/aurelia-validation.d.ts#L561). Trying to do the following:

```ts
import { ValidationConfig, TWBootstrapViewStrategy } from 'aurelia-validation';
...

export function configure(aurelia: Aurelia) {
    aurelia.use
        ...
        .plugin('aurelia-validation', (config: ValidationConfig) => config
            .useViewStrategy(TWBootstrapViewStrategy.AppendToInput))
        ...
}
```

TS compiler fails with:

```bash
error TS2339: Property 'AppendToInput' does not exist on type 'typeof TWBootstrapViewStrategy'.
```

**Comment by Jaans** [comment]
Having the same issue. Normally, it's easy enough to add in a custom_typings `.d.ts` file and extend the interface, but I'm unable to devise such workaround because it is exported as a class and not an interface so no "duck-typing" is available to add in the missing `static` properties. 

All I'm able to do as a workaround is to manually edit the `aurelia-validation.d.ts` file in the JSPM package source to the following:

```
export class TWBootstrapViewStrategy {
    static AppendToInput;
    static AppendToMessage;
}
```

Does anyone have a different workaround that doesn't involve editing the JSPM `.d.ts` file?
