### ISSUE TITLE
Radio button validation error message not working fine

### ISSUE THREAD

**Issue by SivaJonnala** [aurelia/validation#137]
Hi I am Siva Jonnala, 
I am trying to validate the radio buttons  I am not getting the validation error message.
I want to see the validation error message for my requirement. 

My javascript code in my view model is :
        this.selected='';
         this.agreeSelection = ['Yes', 'No'];

	for my validation I have given like this :
		
	.ensure('selected')
            .isNotEmpty()
            .isIn(this.agreeSelection )
            .withMessage('sect any yes or no');

But it is showing nothing even I haven't selected any radiobutton while submitting the form
(Form doesn't submitted , That means validation is working fine but error message is not coming).

**Comment by PWKad** [comment]
Thanks for submitting this / commenting on this.  At this time we are closing this because we have completely re-written and are deprecating the previous feature set.  If you feel this should be re-opened please feel free to review [this blog post](http://blog.durandal.io/2016/05/03/aurelias-new-validation-and-testing-capabilities/) and submit either again on this repository, or on the new [validatejs bridge repository](https://github.com/aurelia/validatejs)

Thanks again!

**Comment by SivaJonnala** [comment]
Thank you @PWKad I have read the blog about the new validationjs. It is looking good to work with new validationjs. I hope it will come with good working exp without any bugs.
