### ISSUE TITLE
globalResources with single file export 

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia/validation#146]
If we eventually reach a point where aurelia-validation is able to have a single file export, we need to know if globalResources is still necessary/or even works. I think it will cause a 404 for validate-custom-attribute.js since only aurelia-validation.js would exist.

**Comment by PWKad** [comment]
Thanks for submitting this / commenting on this.  At this time we are closing this because we have completely re-written and are deprecating the previous feature set.  If you feel this should be re-opened please feel free to review [this blog post](http://blog.durandal.io/2016/05/03/aurelias-new-validation-and-testing-capabilities/) and submit either again on this repository, or on the new [validatejs bridge repository](https://github.com/aurelia/validatejs)

Thanks again!

**Comment by PWKad** [comment]
As a note might not hurt to get this set up in the latest too.
