### ISSUE TITLE
Failing IE test

### ISSUE THREAD

**Issue by jods4** [aurelia/validation#159]
I was trying to make all tests pass in IE, with relative success. Failing tests are caused by fragile timing issues and lack of `TaskQueue` for browsers without `Object.observe`.

But there is one test, which fails in a way that I don't understand and don't have time to debug. Specifically, this assertion:
https://github.com/aurelia/validation/blob/master/test/i18n.spec.js#L182

It validates that the number `300,000,00` is incorrectly formatted for culture `nl-BE` and expects message `moet een getal zijn`, but for a non-obvious reason the message is `is verplicht` in IE, which is the `nl-BE` message for the `required` validator.

**Comment by PWKad** [comment]
Thanks for submitting this / commenting on this.  At this time we are closing this because we have completely re-written and are deprecating the previous feature set.  If you feel this should be re-opened please feel free to review [this blog post](http://blog.durandal.io/2016/05/03/aurelias-new-validation-and-testing-capabilities/) and submit either again on this repository, or on the new [validatejs bridge repository](https://github.com/aurelia/validatejs)

Thanks again!
