### ISSUE TITLE
Discussion: labels for validation messages

### ISSUE THREAD

**Issue by jods4** [aurelia/validation#164]
Part of the thinking toward an `aurelia-validation` refactoring (see #161), I would like to open a discussion open how Aurelia validation message can access a field name / label.

It seems this is currently an oversight from the library, which results in generic "is required." messages without field name. 

This is kinda acceptable when displayed inline.
In my project, I actually got the label from UI inside my own ValidationStrategy but this is not generic.

Most validation libraries also provide a "validation summary" binding that lists all validation error messages. In this scenario you definitely need to include field names / labels.

I think:
Since the validation is currently defined by `.ensure('fieldname').isSomething()` the validation messages could include a placeholder for `fieldname`. 
If the field name in JS code is not the same as for the UI, maybe make it customizable with the config callback or another parameter? Like `.ensure('firstName', config => config.field('First name'))`.

Open point: what about i18n?

**Comment by PWKad** [comment]
Thanks for submitting this / commenting on this.  At this time we are closing this because we have completely re-written and are deprecating the previous feature set.  If you feel this should be re-opened please feel free to review [this blog post](http://blog.durandal.io/2016/05/03/aurelias-new-validation-and-testing-capabilities/) and submit either again on this repository, or on the new [validatejs bridge repository](https://github.com/aurelia/validatejs)

Thanks again!


(As a note this should be better in the latest release)
