### ISSUE TITLE
Improve generated TypeScript declarations

### ISSUE THREAD

**Issue by atsu85** [aurelia/validation#170]
Currently there are basic TypeScript type annotations missing even for the most used methods, even for the method that is used almost every time when validation is used:
https://github.com/aurelia/validation/blob/master/src/validation.js#L28
not to menton methods in ValidationGroup or other classes.

Pull request https://github.com/aurelia/validation/pull/162 from @stephenlautier adds type annotations for many commonly used methods, but it could be improved even more.

**Comment by atsu85** [comment]
Please merge my pull request to resolve this issue: https://github.com/aurelia/validation/pull/171

**Comment by PWKad** [comment]
Thanks for submitting this / commenting on this.  At this time we are closing this because we have completely re-written and are deprecating the previous feature set.  If you feel this should be re-opened please feel free to review [this blog post](http://blog.durandal.io/2016/05/03/aurelias-new-validation-and-testing-capabilities/) and submit either again on this repository, or on the new [validatejs bridge repository](https://github.com/aurelia/validatejs)

Thanks again!
