### ISSUE TITLE
TS definitions

### ISSUE THREAD

**Issue by jods4** [aurelia/validation#180]
The definitions currently available with the pre-beta release are almost unusable without major hand-editing. Many, many types are just `any`. Optional parameters are not marked as such.

**Comment by EisenbergEffect** [comment]
Validation isn't going into beta. None of the plugins are. I should clarify that. The core framework will go beta next week and the plugins will at a later date. Also, major re-work is planned for the Validation library. Feel free to contribute types in a PR at any time and we can get them into the next release.

**Comment by nomack84** [comment]
Hmm, there are many things that will be refactored, the PathObserver class, for instance. So I think it'll be better to wait till the refactor is done to start creating TS related PRs.

**Comment by pwelter34** [comment]
When is the refactor going to happen?  I'd like to see the definitions file get updated.  Willing to do so if its safe.

**Comment by PWKad** [comment]
Thanks for submitting this / commenting on this.  At this time we are closing this because we have completely re-written and are deprecating the previous feature set.  If you feel this should be re-opened please feel free to review [this blog post](http://blog.durandal.io/2016/05/03/aurelias-new-validation-and-testing-capabilities/) and submit either again on this repository, or on the new [validatejs bridge repository](https://github.com/aurelia/validatejs)

Thanks again!
