### ISSUE TITLE
Unhandled promise rejection Error: Error invoking TaskQueue. Check the inner error for details.

### ISSUE THREAD

**Issue by hadrienl** [aurelia/validation#182]
Hi,

I've just installed aurelia-validation with `jspm install aurelia-validation` then, just add `.plugin('aurelia-validation')` in main.js and I have the following error:

![](http://puu.sh/liUbZ/f85554a5b4.png)

**Comment by EisenbergEffect** [comment]
See the gitter channel for information on this. Basically, you probably have forks in package dependencies...multiple versions of certain libraries which is causing you a problem. This could happen as a result of a 3rd party dependency which is dependent on older versions.

**Comment by gabor-farkas** [comment]
I have the same issue. I just downloaded kit-typescript, and ran ```jspm install aurelia-validation```.
Note that running this install also changes the config.js here:
```
  paths: {
    "github:*": "../jspm_packages/github/*",
    "npm:*": "../jspm_packages/npm/*"
  },
```
It removes the ".." from the paths so the kit stops working.
If I restore the paths, and actually inject the validator in app.ts
```
import {Validation} from 'aurelia-validation';
export class App {
  message: string = 'Welcome to Aurelia!';
  static inject() { return [Validation];}
  constructor(validation) {
  }
}
```
Then the same error occurs.

(I understand that this is caused by some misconfiguration, but it's quite hard to get started with aurelia if I have to investigate issues like this upfront. I might be just unlucky but it's actually quite frequent for me with aurelia that simple tutorials just don't work)

**Comment by EisenbergEffect** [comment]
The beginner kits are not designed to have "install" run on them. They are preconfigured for learning with the getting started guide. To move beyond that you will need to use one of our production skeletons. We have added a note to the docs to make this more clear. We are also working on a CLI which will eliminate the need for two different learning paths in the future and make it much easier to get up and running without any caveats. I apologize for the confusion.

**Comment by gabor-farkas** [comment]
Cool, thanks for the clarification!
