### ISSUE TITLE
More informations in ValidationViewStrategy.updateElement

### ISSUE THREAD

**Issue by hadrienl** [aurelia/validation#184]
Hi,

I'd like more information in `ValidationResultProperty` object send to `ValidationViewStrategy.updateElement` to be able to customize my UI callback. Actually, I receive the `failingRule` which is cool, but I don't know what is the control which has been updated. I could retreive it by reading `element.getAttribute('value.bind')` but I'm not sure it will works everytime. Then event if I could find the control name, I don"t have any informations about the configuration of the falling rule. Bref : I'd like to know that `MinimumLengthValidationRule` has fail because the limit was 3 for this input. Maybe just a `fallingRuleReasons` which could be a Number or a Boolean.

**Comment by PWKad** [comment]
Thanks for submitting this / commenting on this.  At this time we are closing this because we have completely re-written and are deprecating the previous feature set.  If you feel this should be re-opened please feel free to review [this blog post](http://blog.durandal.io/2016/05/03/aurelias-new-validation-and-testing-capabilities/) and submit either again on this repository, or on the new [validatejs bridge repository](https://github.com/aurelia/validatejs)

Thanks again!
