### ISSUE TITLE
Validation tries to validate all the fields in all the forms in the VM instead only of the submitted one

### ISSUE THREAD

**Issue by niieani** [aurelia/validation#185]
I have 2 forms inside of one VM. When I click the submit button or otherwise submit the form, `validation` validates the fields of both forms, instead of just the one that was submitted, thus making the validation fail.

**Comment by PWKad** [comment]
Thanks for submitting this / commenting on this.  At this time we are closing this because we have completely re-written and are deprecating the previous feature set.  If you feel this should be re-opened please feel free to review [this blog post](http://blog.durandal.io/2016/05/03/aurelias-new-validation-and-testing-capabilities/) and submit either again on this repository, or on the new [validatejs bridge repository](https://github.com/aurelia/validatejs)

Thanks again!
