### ISSUE TITLE
'Missing' declarations in d.ts

### ISSUE THREAD

**Issue by kdeberni** [aurelia/validation#198]
I found out that some property/method are missing in ayrelia-validation.d.ts.
For example ValidationResult in js have property with name 'properties' - list of unvalid properties. Very useful if one would like to list messages about broken validation.
Another example is 'config:ValidationConfig' property on Validation class.

Those 'missing' declarations are intentional or just an oversight?

**Comment by heruan** [comment]
I have various issues with the `.d.ts` too. For example, starting form `Validation.on` the callback arguments isn't optional in the `.d.ts`, and the compiler fires an error. Then, return values of many functions are typed as `any`, making the `.d.ts` pretty useless.

**Comment by heruan** [comment]
Installing from `master` solved some `.d.ts` issue, but some still hit even `master`; for example `ValidationResult` and `ValidationResultProperty` do not explicitly expose `isValid`/`isDirty` and other properties, making them invisible to a TS user.

**Comment by PWKad** [comment]
Thanks for submitting this / commenting on this.  At this time we are closing this because we have completely re-written and are deprecating the previous feature set.  If you feel this should be re-opened please feel free to review [this blog post](http://blog.durandal.io/2016/05/03/aurelias-new-validation-and-testing-capabilities/) and submit either again on this repository, or on the new [validatejs bridge repository](https://github.com/aurelia/validatejs)

Thanks again!
