### ISSUE TITLE
Path Observer splits the property/expression incorrectly for observation

### ISSUE THREAD

**Issue by corneliutusnea** [aurelia/validation#206]
The Path Observer tries to split the propertyName using "." (dot) and then use that with the observerLocator to look for observers.
https://github.com/aurelia/validation/blob/425840323d4e41917ef83e3ef13dc653ad7bb489/src/path-observer.js#L4

Because of that you can't define validation properties that include array elements:
`.ensure('List["A.B.C.D"].Value').`

Binding to such an expression is valid when used in a view but fails when used in validation.

**Comment by PWKad** [comment]
Good catch, we need to refactor this code to re-use the binding system anyway so leaving this open for now as a reminder about dots.

**Comment by PWKad** [comment]
Thanks for submitting this / commenting on this.  At this time we are closing this because we have completely re-written and are deprecating the previous feature set.  If you feel this should be re-opened please feel free to review [this blog post](http://blog.durandal.io/2016/05/03/aurelias-new-validation-and-testing-capabilities/) and submit either again on this repository, or on the new [validatejs bridge repository](https://github.com/aurelia/validatejs)

Thanks again!
