### ISSUE TITLE
View strategies are missing from the d.ts file

### ISSUE THREAD

**Issue by riddla** [aurelia/validation#207]
I also faced the issue described by @mikeobrien over at https://github.com/aurelia/validation/issues/133.

```error TS2339: Property 'AppendToInput' does not exist on type 'typeof TWBootstrapViewStrategy'.```

**Comment by PWKad** [comment]
Thanks for submitting this / commenting on this.  At this time we are closing this because we have completely re-written and are deprecating the previous feature set.  If you feel this should be re-opened please feel free to review [this blog post](http://blog.durandal.io/2016/05/03/aurelias-new-validation-and-testing-capabilities/) and submit either again on this repository, or on the new [validatejs bridge repository](https://github.com/aurelia/validatejs)

Thanks again!
