### ISSUE TITLE
Validate Specific Groups of Properties in the UI

### ISSUE THREAD

**Issue by EisenbergEffect** [aurelia/validation#212]
@PWKad This may be supported already. I'm not sure, so I wanted to track it here just in case.

We need to be able to have different buttons on a form validate different groups of properties in a screen.

**Comment by PWKad** [comment]
Thanks for submitting this / commenting on this.  At this time we are closing this because we have completely re-written and are deprecating the previous feature set.  If you feel this should be re-opened please feel free to review [this blog post](http://blog.durandal.io/2016/05/03/aurelias-new-validation-and-testing-capabilities/) and submit either again on this repository, or on the new [validatejs bridge repository](https://github.com/aurelia/validatejs)

Thanks again!
