### ISSUE TITLE
Removing validation rules using  .destroy() is not removing the existing validation rules

### ISSUE THREAD

**Issue by jithinoj** [aurelia/validation#213]
I have a scenario, Where I need to **reconfigure the validation rules**. I have used the  `this.validator.destroy(); `method for removing the existing validation rules, which is not removing rules from the `validator` object. Also tried calling  `destroy()` on each validation properties and setting `this.validator` to `null`.  

Is there any method available for removing the validation rules on a property?

**Comment by PWKad** [comment]
Thanks for submitting this / commenting on this.  At this time we are closing this because we have completely re-written and are deprecating the previous feature set.  If you feel this should be re-opened please feel free to review [this blog post](http://blog.durandal.io/2016/05/03/aurelias-new-validation-and-testing-capabilities/) and submit either again on this repository, or on the new [validatejs bridge repository](https://github.com/aurelia/validatejs)

Thanks again!
