### ISSUE TITLE
error handling is not especially helpful

### ISSUE THREAD

**Issue by ariovistus** [aurelia/validation#221]
in the case where code I've hooked in a passes() callback is throwing an exception, this code in validation-property.js:

```
          .catch((err) => {
            throw Error('Unexpected behavior: a validation-rules-collection should always fulfil');
          });
```
is eating err, which has a useful error message and stack trace for me (on chrome, at least), and replacing it with an exception that gives me no useful information, except an error message to grep for in source code.

**Comment by PWKad** [comment]
Thanks for submitting this / commenting on this.  At this time we are closing this because we have completely re-written and are deprecating the previous feature set.  If you feel this should be re-opened please feel free to review [this blog post](http://blog.durandal.io/2016/05/03/aurelias-new-validation-and-testing-capabilities/) and submit either again on this repository, or on the new [validatejs bridge repository](https://github.com/aurelia/validatejs)

Thanks again!
