### ISSUE TITLE
Simplify validation DSL

### ISSUE THREAD

**Issue by stalniy** [aurelia/validation#223]
I see that there is a big/complex DSL around validation. What about adding ability of something like this:
```es6
class UserProfile { 
  @ensure({ presence: true, minlength: 5 })
  name = '';

  @ensure({ presence: true, if: 'isAdult' }) 
  // or @ensure({ presence: true, if: u => u.age >= 18 })
  // or @ensure({ presence: true, unless: u => u.age < 18 })
  profession = null;

  isAdult() {
    return this.age >= 18;
  }
}
```

Doesn't it seem simpler or more straightforward than current version?
```es6
class UserProfile { 
  @ensure(it => it.isNotEmpty().hasLengthBetween(3,10))
  name = '';

  @ensure(it => it.if(u => u.isAdult()).isNotEmpty().endIf()) 
  profession = null;

  isAdult() {
    return this.age >= 18;
  }
}
```

**Comment by PWKad** [comment]
Thanks for submitting this / commenting on this.  At this time we are closing this because we have completely re-written and are deprecating the previous feature set.  If you feel this should be re-opened please feel free to review [this blog post](http://blog.durandal.io/2016/05/03/aurelias-new-validation-and-testing-capabilities/) and submit either again on this repository, or on the new [validatejs bridge repository](https://github.com/aurelia/validatejs)

Thanks again!

**Comment by PWKad** [comment]
As a note the API for validation is changing so any thoughts welcome here - https://github.com/aurelia/validatejs/issues/17
