### ISSUE TITLE
Improve typescript declaration, add missing properties

### ISSUE THREAD

**Issue by OzgurDogan** [aurelia/validation#230]
Please include missing properties for typescript declaration.

The ValidationResultProperty is missing the "isValid" and the "isDirty" properties.
The ValidationResult is missing the "isValid" and the "properties" properties.

**Comment by PWKad** [comment]
Thanks for submitting this / commenting on this.  At this time we are closing this because we have completely re-written and are deprecating the previous feature set.  If you feel this should be re-opened please feel free to review [this blog post](http://blog.durandal.io/2016/05/03/aurelias-new-validation-and-testing-capabilities/) and submit either again on this repository, or on the new [validatejs bridge repository](https://github.com/aurelia/validatejs)

Thanks again!
