### ISSUE TITLE
'AppendToInput' and 'AppendToMessage' properties of 'TWBootstrapViewStrategy' not exposed in TypeScript typings

### ISSUE THREAD

**Issue by Jaans** [aurelia/validation#232]
When setting the view strategy for validation like so:

```
import { ValidationConfig, TWBootstrapViewStrategy } from 'aurelia-validation';
...

export function configure(aurelia: Aurelia) {
    aurelia.use
        ...
        .plugin('aurelia-validation', (config: ValidationConfig) => config
            .useViewStrategy(TWBootstrapViewStrategy.AppendToMessage))
        ...
}
```

then the TypeScript compiler fails with:

```
error TS2339: Property 'AppendToMessage' does not exist on type 'typeof TWBootstrapViewStrategy'.
```

Unfortunately the TypeScript export for `TWBootstrapViewStrategy` is a class and not an interface, so we cannot ["merge" a custom TypeScript interface declaration for it](http://www.typescriptlang.org/docs/handbook/declaration-merging.html) and "duck-type" it to work. So at the moment we manually add (and repeatedly re-add) the property to the JSPM version.

Can you please include it in the `aurelia-validation.d.ts` of the JSPM package?

**Comment by Jaans** [comment]
Update: New aurelia-validation version 0.6.7 now works with webpack to load localised resources.  Yay!! 

However, the typescript declaration file `aurelia-validation.d.ts` is yet to be updated / generated with these static properties.

**Comment by PWKad** [comment]
Thanks for submitting this / commenting on this.  At this time we are closing this because we have completely re-written and are deprecating the previous feature set.  If you feel this should be re-opened please feel free to review [this blog post](http://blog.durandal.io/2016/05/03/aurelias-new-validation-and-testing-capabilities/) and submit either again on this repository, or on the new [validatejs bridge repository](https://github.com/aurelia/validatejs)

Thanks again!
