### ISSUE TITLE
computedFrom doesn't support paths -  based on #149

### ISSUE THREAD

**Issue by jdanyow** [aurelia/validation#234]
@ClareBear85 commented on [Tue Apr 05 2016](https://github.com/aurelia/binding/issues/370)

I updated to aurelia-binding@1.0.0-beta.1.3.1, so that I could do the following: computedFrom - including path. 

```
                    .ensure('baseContent.ValidFromDate', (config) => { config.computedFrom(['baseContent.ValidFromTime', 'baseContent.ValidToDate', 'baseContent.ValidToTime']) })
                        .if(() => {
                            return this.baseContent.ValidFromDate !== null && this.baseContent.ValidFromTime !== null && this.baseContent.ValidToDate !== null && this.baseContent.ValidToTime !== null })
                            .passes( () => { return this.datetimeformat.format(this.baseContent.ValidFromDate, this.baseContent.ValidFromTime) < this.datetimeformat.format(this.baseContent.ValidToDate, this.baseContent.ValidToTime) })
                            .withMessage('< Valid To')
```

![image](https://cloud.githubusercontent.com/assets/7114660/14313249/5c6e1798-fbe8-11e5-865d-5a933754f747.png)

However this doesn't fall into the if statement if 'baseContent.ValidFromTime', 'baseContent.ValidToDate', 'baseContent.ValidToTime' have changed. What am I missing?

**Comment by PWKad** [comment]
Thanks for submitting this / commenting on this.  At this time we are closing this because we have completely re-written and are deprecating the previous feature set.  If you feel this should be re-opened please feel free to review [this blog post](http://blog.durandal.io/2016/05/03/aurelias-new-validation-and-testing-capabilities/) and submit either again on this repository, or on the new [validatejs bridge repository](https://github.com/aurelia/validatejs)

Thanks again!
