### ISSUE TITLE
Add locale messages

### ISSUE THREAD

**Issue by svzosorio** [aurelia/validation#237]
I change the locales of my aplication to es-MX but the return messages is "" 
<img width="330" alt="screen shot 2016-04-13 at 7 36 53 pm" src="https://cloud.githubusercontent.com/assets/5873627/14513592/18a405dc-01af-11e6-9648-83da02b4eb11.png">

**Comment by PWKad** [comment]
Thanks for submitting this / commenting on this.  At this time we are closing this because we have completely re-written and are deprecating the previous feature set.  If you feel this should be re-opened please feel free to review [this blog post](http://blog.durandal.io/2016/05/03/aurelias-new-validation-and-testing-capabilities/) and submit either again on this repository, or on the new [validatejs bridge repository](https://github.com/aurelia/validatejs)

Thanks again!
