### ISSUE TITLE
end to end wireup/prototype

### ISSUE THREAD

**Issue by jdanyow** [aurelia/validation#247]
@PWKad / @EisenbergEffect / anyone who's interested...

I put together an end-to-end wireup with a form, some entities, the binding behavior, a bootstrap renderer and reporter.  The code is here:  https://github.com/jdanyow/skeleton-navigation/tree/validation/skeleton-es2016/src

It uses the existing aurelia-validation and aurelia-validatejs code.  Anything that was changed is in the repo mentioned above under `src/aurelia-validation/`, `src/aurelia-validatejs/` and `src/aurelia-bootstrap-validation/` folders.

When looking at this, it would probably make the most sense to look at `src/app.html`, followed by `src/app.js` then over to `src/aurelia-validation/validate-binding-behavior.js`.

The current code isn't actually validating anything or observing any properties, the ValidateJSValidationReporter just fires a couple errors on an interval to verify things are hooked up.  Will go back and fill in the observation and calls to the validator once we discuss a bit more.

Let me know what you think.  Definitely some questionable items in there... I'm looking at you "NewInstance.of(...).as(...)" :wink:

Here's what it looks like when it's running: [animated gif](http://i.imgur.com/MJ6PkpG.gifv)

**Comment by jdanyow** [comment]
cc @mbroadst

**Comment by EisenbergEffect** [comment]
@PWKad This looks pretty good to me. There are still a few open questions but I think we can resolve them if we can move forward with this. Please review with top priority.

**Comment by mbroadst** [comment]
This looks good to me. As a matter of fact in the past week I've sort of been throwing my eggs into the json-schema basket, so I'm getting more to a point where I'm more focused on the "reporting" and templating side of the equation rather than the validation primitives themselves. Looks like the flexibility exists in this design, so hopefully once this is locked down I can provide a json-schema hookup for it
