### ISSUE TITLE
design/discuss - full "entity" validation

### ISSUE THREAD

**Issue by jods4** [aurelia/validation#252]
After reading Rob's announcement I was curious how a few things actually worked, so I had a very quick look at the code.

Maybe I'm wrong, but my understanding is that `ValidationController` is tied to the UI/bindings. This is not a good thing because it means that Rob's sample code:
```javascript
submit() {
    let errors = this.controller.validate();
    // todo: call server...
}
```
Does not actually check if the _entity_ is valid, but if the _currently displayed bindings_ are. There is a subtle difference between the two:
- Some complex UI scenarios may involve hiding parts of a global form. Maybe a tabbed form, where only the active tab exists in DOM, or a multi-step wizard, or virtualized controls.
- You may define validation rules on properties that are set by code rather by a binding in the UI.

In the end, it's important to be able to determine that the entity is not fully valid and display a corresponding message to the user.
It is my understanding that one would need to:
- use `Validator` to properly validate the entity;
- call `ValidatorController.validate()` to ensure all errors are highlighted in the UI;
- code a custom component to display the validation messages from `Validator` that are not bindings inside the UI, as `validation-errors` would not include them.

I am also curious how async validation could be added in the current design? I am happy that we got rid of all the Promises in the old validation library, as the most common path should be sync for simplicity and perf, but I also think that an opt-in possibility of using async validation is necessary.

**Comment by jdanyow** [comment]
I agree with all this.  In fact, when work on this started we were going in a direction where entities were registered with the controller.  A lot of the feedback we got was pushing for what I would call "ui centric" / "non entity" or "partial entity" validation which is why the alpha focuses on those types of workflows.

What if we added `addObject(object, rules = null)` and `removeObject(object)` methods to the controller?  This would opt you into "whole entity" style validation.  Maybe it wouldn't change the behavior much, the primary difference would be when `controller.validate()` is invoked, the existing behavior (validate the bindings) would execute along with validating all the objects.  What do you think?

Regarding async validation- any thoughts on how that should work are welcome.  I wonder if we should add methods to the controller for `addError(error, object, property = null)` and `removeError(error)`.  Then people can execute their async rules when they want and push the errors into the controller as-needed?  To me, async rule === expensive rule, so we need a design that gives devs absolute control over when they're executed.  Thoughts?

**Comment by EisenbergEffect** [comment]
I was actually thinking it would be nice to have the `addError` and `removeError` apis in general so you always have that low-level type of control. Seems like any async check could be handled that way as well.

**Comment by EisenbergEffect** [comment]
As a use case, the create account form that does a check for unique user name.

**Comment by jods4** [comment]
### Full entity validation
I am not sure `addObject/removeObject` is the right API. It's tedious when swapping an entity in a VM and it implies the validation controller works with several object, which isn't very clear to me.

Something like `.for(object, rules=null)` (can be called multiple times) seems better to me. I was tempted to use `.on()` but maybe we should keep it for the day controller raises events?

So pattern would be: (a) inject a controller if you only care about validating your UI bindings; (b) inject and call `.for(object)` if you want full object validation regardless of UI.

### Add/remove error API
I think this is a welcome addition. It supports things that are hard to validate at the model-level.

For example, if you have a strongly typed (TS) model with a `Person` property, and a custom person picker control. What happens if the user types an incorrect name in the picker? This is incorrect but is hard to validate on the model itself (maybe by using `undefined` vs `null`... meh). With an API, the custom control could report that easily.

### Async validation
I don't think `addError()` is right for that. The problem is, in your VM `.save()` method you need to know if the entity is fully valid or not. If there are async validations you need a way to wait for their completion. `Promise` seems the right tool here.

I think validatejs has the correct approach. You can easily write validators by returning a value or a Promise. Then when checking, they have a sync and an async (`validate.async()`) method so that you don't get complexity when you don't need it. `aurelia-validation` could expose the same set of API, that would be nice.

**Comment by adarshpastakia** [comment]
Since this is 'Design Questions' thought i'd add something here instead of a new issue.

i have a couple of problems with the new validation plugin, firstly it forces me to inject the controller on my view rather than the data-model, secondly how to validate a complex data model

```js
export class Hotel {
  id;
  @required
  name;
  @required
  countryCode;
  @required
  cityCode;
  @required
  phone;

  languages: Map<string, HotelLanguage> = {
    en: new HotelLanguage()
  };

  validate() {
    return new Promise((resolve, reject) => {
      var promises = [this.validation.validate()];
      var _langErrors = '';
      _.forEach(this.languages, (lang: any, key: string) => {
        if (key == 'undefined' || lang == undefined) return;
        promises.push(lang.validate().catch(e => {
          _langErrors += `${key},`;
          throw e;
        }));
      });
      Promise.all(promises)
        .then(() => {
          resolve();
        })
        .catch(() => {
          reject({
            errors: (_langErrors || '').replace(/,$/, ''),
          });
        });
    });
  }
}

export class HotelLanguage {
  @required
  title;
  @required
  description;
  @required
  amenities;
}
```

with the earlier validation plugin i had instantiated the validation in each model instance, so in the main data model i had a validate method that would iterate through the languages validating each model individually since there is a single form that switches between languages, similar to adding content in apple or google app stores. given the new validate plugin I'm not sure how this can be accomplished.

**Comment by jods4** [comment]
@adarshpastakia Couple remarks:
> it forces me to inject the controller on my view rather than the data-model

Not sure I understand the issue 

Second, you don't need to juggle with Promises like that anymore. That was the old Aurelia validation model, but currently the new one is sync only (hopefully an opt-in async model will be added).

How to validate a complex model is a discussion that depends on your underlying validation framework (`aurelia-validatejs` ?). In this case the cleanest way is probably to create a custom validator that validates the object values of a map. And then:
```javascript
@validateMap
languages: Map<string, HotelLanguage>
```

**Comment by jdanyow** [comment]
@jods4 the validation controller does aim to support multiple entities/objects.  We haven't really showcased that yet.  Here's a simple/contrived example:

https://gist.run/?id=520a4b5f61e385212a27c76bcb6f2da4

**Comment by jods4** [comment]
@jdanyow Interesting, I suppose that it works because you pass an explicit ruleset with `& validate:rules`?

**Comment by jdanyow** [comment]
The rules are passed into the decorator because the objects are POJOs- it's not a requirement for multi-entity controllers.  

If the objects were an instance of a class, and rules had been defined on the class definition using the fluent API or decorators, there would be no need to pass in the rules because aurelia-validatejs could look them up in the metadata:  https://github.com/aurelia/validatejs/blob/master/src/validator.js#L9-L11

That's why the `rule` argument optional in the `addObject(object, rules = null)` and `removeObject(object)` proposal.  If object is a POJO, you'd need to pass in the rules.  Otherwise you can simply pass in the class instance.

**Comment by jdanyow** [comment]
Also worth mentioning the Validator interface has a `validateObject` method, but it's not used **yet**.... We do want to figure this out...  

https://github.com/aurelia/validatejs/blob/master/src/validator.js#L36

**Comment by jods4** [comment]
@jdanyow that was not what troubled me. It was more: "how does the validation controller know which entity a rule is linked to"?
Looking at the code again, I notice that it works purely at the binding/DOM element level and doesn't care about entities at all.

Going back to the initial API, if we introduce `addObject`, it would be nice to also have `clearObjects()` so that consumers don't have to keep track of added references when they want to swap in a new entity.

One thing that is a bit missing and which could aleviate the need for `addObject` is the concept of a validation group: put several objects with rules inside a single collection, which is itself validatable.
This might come in handy. 
It also means that you could pass that to the controller if you want to validate multiple entities and keep a simple `.for(object)` api (and no array allocation in the common case).

**Comment by jdanyow** [comment]
Right- the original version was sort of rolling the rules, behavior and entity into one.  In the new version the rules, behavior and entity are separated.  Currently there's only one API for marrying them back together in a UI: the `validate` decorator.  This is fine for simple "I want to validate the fields I'm displaying" scenarios and even more advanced, multi-entity scenarios, as long as the stuff you want to validate is data-bound, but lacking in the scenarios mentioned in this thread.

We need to decide on nice way to bring whole entity validation into the mix, as well as async workflows.

I think we agree that we should add the `addError(error, object, property = null)` and `removeError(error)` APIs as a starting point for async support.

Does the `addObject(object, rules = null)`, `removeObject(object)`, `removeAllObjects()` sound good?  For convenience we could probably come up with some sort of custom attribute that could automate that add/remove work when the `myEntity` property changes, and when it's bind and unbind are called... something like `validate.bind="myObject"` although it probably should support passing in the rules for POJO scenarios and potentially multiple objects....

I was also thinking about overloading the existing `validate` and `reset` methods on the controller to increase flexibility: 
```js
validate()  // existing API
validate(object)
validate(object, propertyName)
reset() // existing API
reset(object)
reset(object, propertyName)
```

what do you think?  getting closer to what's needed?

**Comment by adarshpastakia** [comment]
@jods4 the ValidationController needs to be injected in the view-model of the view that has `& validate`, this might a bit long but this is an example of my form which is built using custom elements

```html
<template>
  <ui-form submit.trigger="doUpdate()">
    <ui-input value.bind="model.name & validate">Name</ui-input>
    <ui-input value.bind="model.countryCode & validate">Country Code</ui-input>
    
    <ui-combo options.bind="model.languages | keys" value.bind="language"></ui-combo>
    <ui-input value.bind="model.languages[language].title & validate">Title</ui-input>
    <ui-textarea value.bind="model.languages[language].description & validate">Description</ui-textarea>
    <ui-textarea value.bind="model.languages[language].amenities & validate">Amenities</ui-textarea>
  </ui-form>
</template>
```
```ts
@autoinject
export class MyForm {
  model;
  language;
  constructor() {
    this.model = new Hotel();
  }
}

export class Hotel {
  id;
  @required
  name;
  @required
  countryCode;
  @required
  cityCode;
  @required
  phone;

  languages: Map<string, HotelLanguage> = {
    en: new HotelLanguage(),
    es: new HotelLanguage(),
    fr: new HotelLanguage()
  };
}

export class HotelLanguage {
  @required
  title;
  @required
  description;
  @required
  amenities;
}
```

Now unless i inject ValidationController in the `MyForm` class the validation doesn't work, i tried injecting an instance into the `ui-form` custom element and i tried it in the model, neither of which worked.

Also incase i happen to have two forms in the same view how is it possible to validate them individually without having to compose them from two separate view-models.

As for custom validator, could you provide a few tips how to get started, in the old plugin i could add a custom validation to the ValidationGroup prototype

**Comment by adarshpastakia** [comment]
@jdanyow i like @jods4's suggestion of using `.for(object)`

> So pattern would be: (a) inject a controller if you only care about validating your UI bindings; (b) inject and call .for(object) if you want full object validation regardless of UI.

but would that make it possible to have the ValidationController injected in the data-model instead of the view, I'm not sure if it is the correct practice but i like having the validation to be controlled from the data-model and not the view, so when instantiating a data-model one could just call `validationController.for(this)`. 

I'm trying to avoid having to keep injecting ValidationController into every view that would have a form, when using the old plugin i had a validation object instantiated in a `BaseModel` class  which was extended in all my data-models and bound the model's validation to the form, that way i could also have two forms in the same view.

**Comment by jods4** [comment]
I think is thread is starting to go into too many tangents.

I have many things to say, but should we split this into distinct pieces (my bad for starting an overly generic discussion).

In this thread I can find the following topics:
- An equivalent for ValidationGroup in the ASP.NET sense, which enables having more than one form/set of validation per VM?
- Request for a validator code sample that validates all objects in a map or an array.
- `addError` / `removeError` to enlist errors from bindings or value converters not coming from the model.
- async validation
- How to do a full entity validation. BTW I happen to like your `.validate(object)` **a lot**. It makes a lot of sense, this is how it should be used! Additional API like `addObject()` and `removeObject()`are not intuitive, nor needed.
- Possible validation "bags", that aggregates various entities into a single validation. Kinda overlaps with the request for validator code above.

**Comment by jdanyow** [comment]
@jods4, @adarshpastakia heads up- @jsobell has opened an issue for the async piece of this here: https://github.com/aurelia/validatejs/issues/93

let's continue the discussion around "full entity" validation here.  I'll update the title of this issue accordingly.

**Comment by jods4** [comment]
I have started spawing child issues for the various topics that I listed above. I'm updating the list as I go.

@jdanyow about the full entity validation, I think the idea of an `.validate(object)` API feels just right.
If you only want to validate UI fields, you can mindlessly call `.validate()` or `.validate(object)` and they just works. If you want to be sure that an object is completely valid, even non-bound properties, you call `.validate(object)`. That's simple and intuitive, I think.

**Comment by jdanyow** [comment]
closing- this was added in friday's release.
