### ISSUE TITLE
ValidationRenderer and MaterialDesignLite

### ISSUE THREAD

**Issue by crabulik** [aurelia/validation#273]
Hi all. I have such issue:
We use MaterialDesignLite library in out project. 
We created ValidationRenderer, and in the method "render(error, target)" it's adds a span element with the error message and sets class 'is-invalid' to '.mdl-textfield' to the control group. As validateTrigger we use 'blur' value.
All work fine except one situation: When you start changing something in mdl textfield, mdl automaticaly removes class 'is-invalid' from that textfield. But, if you after that returns value of this textfield to the previous value before 'blur' trigger, ValidationRenderer won't run method "render(error, target)".
Is it possible somhow to fire the method "render(error, target)" after each exit from the control, even if the value of that control haven't changed?

**Comment by jdanyow** [comment]
@crabulik we have a new release with changes to the ValidationRenderer API. Give the new release a try and let us know if your issue is resolved.

If you still have an issue, please put together a gist that reproduces the issue and post a question to the aurelia validation gitter channel or stackoverflow and someone will help you with a fix.

https://gist.github.com/jdanyow/3625244afe4f188785190b23f2e7f472
