### ISSUE TITLE
.when clause silent fail on ambiguous use

### ISSUE THREAD

**Issue by jsobell** [aurelia/validation#285]
Applying the `.when` clause to the `ensure` statement is accepted but stops the subsequent rules being applied.
Let's either disallow this, ensure that `.when` can only be applied against a rule, or (best still) allow the `.when` to apply to the entire rule list so it doesn't need duplicating.
Currently we need:
```
      .ensure((m: App) => m.email)
        .required().when((m:App) => m.newsletter===true)
        .email().when((m:App) => m.newsletter===true)
      .on(App);
```
Currently fails silently but would be much nice if supported:
```
      .ensure((m: App) => m.email).when((m:App) => m.newsletter===true)
        .required()
        .email()
      .on(App);
```

**Comment by jdanyow** [comment]
The ambiguous use is definitely a bug. We should look into supporting the shortcut as well.

**Comment by jdanyow** [comment]
@jsobell - I tested this, it doesn't fail silently- `.ensure(...).when(...)` throws the following error is thrown when the rules are defined

```
TypeError: Object doesn't support property or method 'when'
```

**Comment by jsobell** [comment]
Sorry, you're quite right.
It's a tricky one, because any error during assignment will prevent that block of rules being assigned, and unless the developer looks in the console they won't know.
Worse than that is if there is a condition in rule expression definition that fails during runtime.
It would be nice is 'ensure' somehow marked a rule as in definition then any subsequent validation attempt with any unterminated definition failed.
May be overkill, but it makes me uncomfortable to have a situation where validation defaults to success when an error occurs somewhere.

**Comment by jdanyow** [comment]
There's nothing we can do- the error that occurs when writing `ValidationRules.ensure('foo').when(...)` is the same error you'd get if you wrote `window.someMethodThatDoesNotExist()` in your file. There's no opportunity for the validation library to intercept that call because the method does not exist. TypeScript users won't run into this issue because they'll get a transpilation-time error saying the method does not exists (and the red squiggly line etc).

Let's tackle any of the other scenarios that came up in this discussion in separate, focused issues with gists that demonstrate the issue.
