### ISSUE TITLE
Is it possible to prioritise validation rules and cancel the validation of expensive rules?

### ISSUE THREAD

**Issue by jdanyow** [aurelia/validation#289]
@richardbartley commented on [Wed Jun 15 2016](https://github.com/aurelia/validatejs/issues/83)

There are simple rules, i.e. required, max length, etc and these are cheap to validate.  If there is an expensive service / database validation rule, can we prioritise the rules and defer execution of the expensive rule until the simple ones pass ok?

---

@EisenbergEffect commented on [Sat Jul 09 2016](https://github.com/aurelia/validatejs/issues/83#issuecomment-231516365)

@jdanyow Can this be closed as a duplicate since there's heavy discussion on async rules in other issues?

---

@jdanyow commented on [Sat Jul 09 2016](https://github.com/aurelia/validatejs/issues/83#issuecomment-231528673)

I was keeping it open as a reference/reminder

**Comment by jsobell** [comment]
This relates to a 'bail' feature, which honours the order of the rules and stops validating on the first failure (of the rule chain against that property).
In this way the priority can be inferred by the rule order, but a more advanced scenario was also suggested by @jdanyow that we have actual priorities, and subsequent expensive rules only fire if all of the lower priority rules succeed, even those on other properties.
In theory there could potentially be a complex hierarchical rule structure with some rules resolving based on other rule results, but this stuff is getting so complex that it is most likely easier to implement in your code.
Since the latest solution allows multiple controllers, you can group expensive rules into another controller instance and chain the validation of those only if the main controller passes without errors.

**Comment by jdanyow** [comment]
closing this because we are tracking it in #301
