### ISSUE TITLE
Unable to parse accessor function on ensure in Firefox

### ISSUE THREAD

**Issue by genadis** [aurelia/validation#324]
**I'm submitting a bug report**

* **Library Version:**
0.12.3

**Please tell us about your environment:**
* **Operating System:**
Windows [10]

* **Node Version:**
4.x LTS

* **NPM Version:**
3.10.6

* **JSPM OR Webpack AND Version**
JSPM 0.16.41

* **Browser:**
Firefox 47.0.1

* **Language:**
ESNext

**Current behavior:**
When using property access expression:
```
ValidationRules.ensure((f: MyClass) => f.classProperty)
  ...
```
Exception is thrown only in Firefox (Chrome and Edge work without issues).
```
"Unhandled rejection Error: (SystemJS) Unable to parse accessor function:
	function (f) {
	"use strict";
	
	    return f.classProperty;
	  }
	ValidationParser</ValidationParser.prototype.getAccessorExpression@http://localhost:9000/jspm_packages/npm/aurelia-validation@0.12.3/implementation/validation-parser.js:43:23
```

If using property name string:
```
ValidationRules.ensure('classProperty')
  ...
```
Everything works on Firefox as well

**Comment by Ma3yTa** [comment]
It because ESNext transpiler added "use strict";

@jdanyow I think need update https://github.com/aurelia/validation/blob/9bb0db99453f264847365df1726b841334de15e7/dist/es2015/implementation/validation-parser.js

``classic`` regex to `^function\s*\([$_\w\d]+\)\s*\{[\s]*("use strict";)?[\s]*return\s+[$_\w\d]+\.([$_\w\d]+)\s*;?\s*\}$`

**Comment by rborosak** [comment]
I'm having the same problem. I'm using aurelia-validation 0.13.1 and Typescript (version 2.1.0-dev.20161018)
 
The problem is in all browsers.

`constructor(public validationControllerFactory: ValidationControllerFactory) {
        super();

        this.businessPartner = new BusinessPartnerDto();
        this.validationController = this.validationControllerFactory.createForCurrentScope();
        ValidationRules.ensure((x: BusinessPartnerDto) => x.name).required()
            .ensure((x: BusinessPartnerDto) => x.zip).required()
            .on(this.businessPartner);
    }`

This is the output in the console.
Inner Error:
Message: Unable to parse accessor function:
(x) => x.name
Inner Error Stack:
Error: Unable to parse accessor function:
(x) => x.name
    at ValidationParser.getAccessorExpression (http://localhost:9000/scripts/app-bundle.js:6715:23)
    at ValidationParser.parseProperty (http://localhost:9000/scripts/app-bundle.js:6723:33)
    at FluentEnsure.ensure (http://localhost:9000/scripts/app-bundle.js:7086:67)
    at Function.ValidationRules.ensure (http://localhost:9000/scripts/app-bundle.js:7135:61)
    at new BusinessPartner (http://localhost:9000/scripts/app-bundle.js:1843:50)

If I use a property name it works.
