### ISSUE TITLE
Validation Renderer has no way to provide success styling

### ISSUE THREAD

**Issue by Slimfit** [aurelia/validation#356]
**I'm submitting a feature request**

**Current behavior:**
I am able to create a custom validation renderer that detects when an element has become invalid. With this we can apply error styling and then we can detect when that element is transitioning from an invalid state, back to a valid state and I can then apply success styling. As seen here:

```
    render(instruction: RenderInstruction) {
       for (let {error, elements} of instruction.unrender) {
            for (let element of elements) {
                this.remove(element, error);
            }
        }

        for (let {error, elements} of instruction.render) {
            for (let element of elements) {
                this.add(element, error);
            }
        }
    }

    private add(element: Element, error: ValidationError) {
        // Add error styling
    }

    private remove(element: Element, error: ValidationError) {
        // Remove error styling
        // Add success styling
    }
```

But how would I apply success styling when the element was never invalid? I can see in my custom renderer that the render function is called, but the RenderInstruction of kind "validate" contains no elements for me to add styling to. On a new form, on a valid field, the RenderInstruction provided to the render method on my custom renderer looks like this:

```
kind: "validate"
render: Array[0]
unrender:Array[0]
```

As you can see, I have no way of knowing which elements were validated successfully therefore cannot apply styling.

Perhaps adding an unrender() event on the ValidationRenderer or a new `kind` on `RenderInstruction` could work?

**Comment by EisenbergEffect** [comment]
@jdanyow You may have a solution for this already but I marked this as an enhancement. Minimally, I think we would need some documentation on how to handle this.

**Comment by jdanyow** [comment]
Added this to the beta milestone- @Slimfit if you need an immediate workaround you could try doing something with the controller's `bindings` Map and it's `getAssociatedElements` method:

```js
for ([binding] of controller.bindings) {
  const info = getPropertyInfo(binding.sourceExpression, binding.source);
  const elements = controller.getAssociatedElements(info);
  ...
  ...
}
```

The code for `getPropertyInfo` is [here](https://github.com/aurelia/validation/blob/master/src/property-info.ts).

**Comment by Slimfit** [comment]
Thanks for the tip and the quick response!

**Comment by jdanyow** [comment]
I think this might require a change to the `Validator` interface, and some upstream APIs like the `ValidationRenderer`.

The current version (below) returns `Promise<ValidationError[]>`, which tells us what is invalid but provides no information on what exactly was validated.

Similarly, the `ValidationRenderer` is very _"error-centric"_. It's all about rendering and un-rendering _**errors**_.

---

Consider the following (salesforce) UI:

---

![change-password](http://i.imgur.com/TUbqLE9.png)

---

To support something like this we'd need to refactor the Validator to return the rules that were validated and whether they were valid or invalid... 

Instead of:

```ts
validateProperty(...): Promise<ValidationError[]>;
```

We'd need something like:

```ts
validateProperty(...): Promise<ValidateResult[]>;

interface ValidateResult {
  rule: any;
  object: any;
  propertyName?: string;
  error: ValidationError|null;
}
```

This would enable telling the renderer exactly what checked out and what failed. It would also enable adding some more targeted templating facilities. For example, today we can data-bind to the errors associated with an element or set of elements using the `validation-errors` custom attribute. With these changes we could enable data-binding to whether a specific rule or set of rules are valid or invalid.

@EisenbergEffect, @Slimfit, @jsobell, anyone, thoughts? We haven't put the beta stamp on this yet so now would be the time to do something breaking/intrusive like this. @jsobell you and I may have discussed something like this in the past, I can't remember, maybe I didn't quite "get it" at the time.

---

*For reference, current `Validator` interface*:
```ts
/**
 * Validates.
 * Responsible for validating objects and properties.
 */
export abstract class Validator {
  /**
   * Validates the specified property.
   * @param object The object to validate.
   * @param propertyName The name of the property to validate.
   * @param rules Optional. If unspecified, the implementation should lookup the rules for the 
   * specified object. This may not be possible for all implementations of this interface.
   */
  public abstract validateProperty(object: any, propertyName: string, rules?: any): Promise<ValidationError[]>;

  /**
   * Validates all rules for specified object and it's properties.
   * @param object The object to validate.
   * @param rules Optional. If unspecified, the implementation should lookup the rules for the 
   * specified object. This may not be possible for all implementations of this interface.
   */
  public abstract validateObject(object: any, rules?: any): Promise<ValidationError[]>;
}
```

**Comment by jsobell** [comment]
OK, quick brain dump because it's 11:30pm here and my synapses are shutting down...

I have no issue making the change you suggest, as it should work around most of these problems, and this is one aspect I was wurbling on about when I mentioned needing more information in the renderer, but I think is also related to the discussion about having custom rules associated or 'bound' to arbitrary visual elements.
This is one of those tricky crossovers between object and UI validation. Because we can have object level rules, but the user wants the results reflected on-screen, what binds the object level rule to anything in the DOM? As far as validation feedback is concerned we don't care if the rule is linked to an input field or a span, as long as we can display the error.
If we implement the solution where the user is handed a list of both property validation result and the related DOM entity, we really need to provide the DOM elements that they consider related even if they were not validation-bound inputs.

A simple example might be that firstname+lastname are less than 50 characters. We add this as a model rule, but it's not linked to one input field, so the user wants the error displayed below those two fields. When the renderer is called, it has no visual element associated, so how does the user associate this with a point in the DOM to display the error or the green 'OK' result discussed by the OP?

My original suggestion was that all Model level rules have a fake property or 'ID', so we could have a custom attribute anywhere on the form to flag the location (or locations) to be passed to the renderer, and in the above example it would probably be on a `div` enclosing first and last name input fields.

Essentially, once we start raising events intended for UI feedback (even though they are really only property feedback) we need to allow this to happen, as moving the error-centric to be rule-centric needs to be able to provide enough details to allow ui-centric coding when required.

Treacherous partly gets around this by always having the entire collection of passed and failed rules available (as your solution would do), and you can request the message and status of any property by name, even if that property is an object level pseudo-property/ID/tag.

**Comment by EisenbergEffect** [comment]
I would support the change. It's a more flexible design and similar to what I've seen done in other libraries.
