### ISSUE TITLE
feat(validation) enhance ValidationController.validate with optional 'object' parameter 

### ISSUE THREAD

**Issue by dkent600** [aurelia/validation#376]
Currently ValidateInstruction requires the `object` property.

This means, in Typescript at least, that I cannot validate  _all_ objects instances with a given set of rules.  (Nor can I narrow the same down to a single property on all object instances.)

This ability aids with decoupling modules.

This would look like:

`ValidationController.validate({ rules: someRules })`

or

`ValidationController.validate({ propertyName: name })`

or 

`ValidationController.validate({ propertyName: name , rules: someRules })`

**Comment by jdanyow** [comment]
Currently `validate` takes zero parameters or a `ValidateInstruction` which looks like this:

```ts
export interface ValidateInstruction {
  /**
   * The object to validate.
   */
  object: any;

  /**
   * The property to validate. Optional.
   */
  propertyName?: any;

  /**
   * The rules to validate. Optional.
   */
  rules?: any;
}
```

`object` is required because the controller might have many "types" of objects. 

If we allow `propertyName` or `rules` to be specified without indicating which object to validate we'll need to think through and document the different edge cases that can arise as a result.

**Comment by dkent600** [comment]
@jdanyow Thank you for the correction and clarification on that.  

One option would be to pass in the `object` param as null or undefined.  

An additional option providing maximum flexibility would be to redefine that parameter as an array, enabling us to supply any arbitrary set of objects.

**Comment by jdanyow** [comment]
Closing this- not going to change the signature of this method at this time.
