### ISSUE TITLE
Stand alone package

### ISSUE THREAD

**Issue by akircher** [aurelia/validation#405]
**I'm submitting a feature request**

Right now this library is strongly coupled with the aurelia framework because of its dependencies on `aurelia-templating` and `aurelia-binding` among others.  It would be great if it could be bundled as a standalone package for usage outside the framework.  My use case is trying to integrate it as a plugin to PouchDB.

**Comment by jdanyow** [comment]
It's true, the binding and templating are deps for UI stuff like the `& validate` binding behavior, however forking the UI parts to another package would not negate the need for binding because binding's parser is used to interpret validation message expressions and property accessor expressions.

That said, aurelia-validation works in node already so there would be little benefit to dropping these deps, other than making your node_modules folder a tiny bit slimmer.
