### ISSUE TITLE
Reset validation

### ISSUE THREAD

**Issue by Mordred** [aurelia/validation#44]
Is it possible to reset validation? I need to reuse the form after AJAX action.

**Comment by janvanderhaegen** [comment]
Hey @Mordred ,
you can now call .clear() on the validation.result, which resets it, as in this example: http://aurelia.io/validation/#/on-validate
This is not part of the release yet, so you'd need to npm install aurelia-validation=github:aurelia/validation@master to play around with it before we release another update.

If this does not address your use case, we'd love to know.

Thanks for the suggestion!

Jan

**Comment by Mordred** [comment]
@janvanderhaegen .clear() is working. There is problem that you usually do something like this:

```js
        this.password = this.currentPassword = this.passwordCheck = '';
        this.validation.result.clear();
```

First reset all fields to empty string and then call clear(). Validation will run again after clear, because inputs has changed. I have created demo: http://plnkr.co/edit/VbrVVG?p=preview

Calling `clear` inside `setTimeout` solves this problem, but I'm not sure how long should timeout wait.

**Comment by janvanderhaegen** [comment]
Hmmm I can probably fix this from within the plugin, I don't want you to have to call clear inside a setTimeout ;-)

**Comment by janvanderhaegen** [comment]
Still working on this, but a fix is on the way :-)

**Comment by janvanderhaegen** [comment]
Ok I changed clear, but instead of calling
``` javascript
this.validation.result.clear();
```
you have to call
``` javascript
this.validation.clear();
```
The validation will then eagerly fetch the new 'reset' form values, and reset the result to valid, non-dirty.  Once the observers notify of the form resetting, the validation already evaluated the latest value and will ignore that.

See the example:  http://aurelia.io/validation/#/on-validate

This change has not been released yet, but you can test the latest bits:
```
jspm install aurelia-validation=github:aurelia/validation
```

Please do let me know if there are issues with this new implementation :)

**Comment by Mordred** [comment]
Great work! Thank you
