### ISSUE TITLE
postinstall shouldn't run npm uninstall

### ISSUE THREAD

**Issue by jmezach** [aurelia/validation#446]
**I'm submitting a bug report**

* **Library Version:**
1.0.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x

* **Node Version:**
7.7.1

* **NPM Version:**
5.0.1

* **JSPM OR Webpack AND Version**
webpack 2.4.1

* **Browser:**
all

* **Language:**
TypeScript 2.3.1

**Current behavior:**
The aurelia-validation npm package has a postinstall hook which runs npm uninstall for a set of packages. We've recently upgraded to npm 5 which seems to first install all the packages including any development dependencies. We're working with our own npm feed thus it fails to find some of the development dependencies since we don't need those ourselves.

**Expected/desired behavior:**

I think the postinstall hook shouldn't be uninstalling packages in the first place. If they aren't needed they shouldn't be a dependency in the first place. What's the reasoning behind uninstalling these packages in the postinstall hook?

* **What is the expected behavior?**
npm install works in our environment without having to put all the dev dependencies for aurelia-validation into our own feed.

* **What is the motivation / use case for changing the behavior?**
More consistent and faster installations of the package.

**Comment by B3zo0** [comment]
Hi @jmezach!
I can answer your question, one of the dependencies called @typedoc installs these typings what are not required by us and therefore the post install script. These are removed because they can cause typescript errors in your project. You can take a look at this pr and below the issues at typedoc that why they had to put the typings in to dependencies.
https://github.com/TypeStrong/typedoc/pull/434
