### ISSUE TITLE
Bug in "Calling Validate" example

### ISSUE THREAD

**Issue by Zoltu** [aurelia/validation#54]
http://aurelia.io/validation/#/form-submission
> this example always has the submit button enabled

When I view the page (in Chrome) the submit button is disabled and stays disabled no matter what is in the input box.

**Comment by janvanderhaegen** [comment]
Ugh... Sorry about that.
The issue is with the disabled.bind="!validation.isValidating". This is a double-negative, it should have been disabled when the validation is validating (like a long running AJAX call), but if you disable it when it's not validating, well there's no chance for the user to ever have it validate... 

Thank you for reporting!
