### ISSUE TITLE
how do I reference `this` with validation?

### ISSUE THREAD

**Issue by chovy** [aurelia/validation#68]
I'm currently doing this:

```
  @ensure(function(it){
    it.isNotEmpty()
      .hasLengthBetween(3,100);
  })
    name = ''; //needs to be `this.thing.name` somehow
```

But I need to reference an object like `this.thing.name` instead. I'm moving the properties of the view model to a single object as children. so instead of `name` in my view I do `thing.name` etc. etc.

I can't figure out how to get the `@ensure` validation to work if I make this change.

**Comment by CharlesPockert** [comment]
You need to provide a validation hint so that the validation framework knows which property name is bound in the view:

```
<input value.bind="this.thing.name" validate="name">...
```

Without the `validate` hint, since the view strategy for applying classes etc uses only the view, it has no VM context so it has no way of knowing from the string "this.thing.name" what the actual property name is. The validate hint gives it the information it needs.

Check out this:

https://github.com/aurelia/validation/issues/45

**Comment by janvanderhaegen** [comment]
Hey @chovy , 

if you're using nested properies, the @ensure decorator won't work anymore and you'll have to use the fluent API.
See http://stackoverflow.com/questions/30518642/how-to-use-aurelia-validate-with-a-object-properties-to-validate ;-)

**Comment by chovy** [comment]
Thanks. I thought I had asked this question already. Sorry about that.

**Comment by janvanderhaegen** [comment]
No worries, good to have it documented!!!
