### ISSUE TITLE
Support both model-first and view-first implementations

### ISSUE THREAD

**Issue by janvanderhaegen** [aurelia/validation#7]
The framework currently supports model-first: use a fluent API on your model to create the 'validation' object.
We can add custom attributes so that those who want to, can create the 'validation' object completely using attributes.

**Comment by PWKad** [comment]
Thanks for submitting this / commenting on this.  At this time we are closing this because we have completely re-written and are deprecating the previous feature set.  If you feel this should be re-opened please feel free to review [this blog post](http://blog.durandal.io/2016/05/03/aurelias-new-validation-and-testing-capabilities/) and submit either again on this repository, or on the new [validatejs bridge repository](https://github.com/aurelia/validatejs)

Thanks again!
