### ISSUE TITLE
Validation UI does not work when validation is abstracted to a model.

### ISSUE THREAD

**Issue by singledigit** [aurelia/validation#85]
Hey Jan, Before this became an official part of Aurelia, you and I had a conversation about this and you had a work around. I cannot, for the life of me, find it. Basic issue is, if I create a separate model and store my validation there. Then inject that model into my current viewmodel, tha validation works, but the UI does not. If I copy everything into the current viewmodel then it works fine. I really need the ability to be able to store validation centrally to the model and then be able to use the model anywhere.

**Comment by bychkov** [comment]
I came across the same issue. I tried to collocate validation with my model and when I do this, I do not get UI prompts. Could you please post workaround OP talked about?

**Comment by janvanderhaegen** [comment]
Hey guys,
sorry about the late reply, was ill and on holiday, not a fun combination :(

Was this it? https://github.com/aurelia/validation/blob/master/doc/Intro.md#how-are-elements-and-validation-rules-matched

**Comment by PWKad** [comment]
Thanks for submitting this / commenting on this.  At this time we are closing this because we have completely re-written and are deprecating the previous feature set.  If you feel this should be re-opened please feel free to review [this blog post](http://blog.durandal.io/2016/05/03/aurelias-new-validation-and-testing-capabilities/) and submit either again on this repository, or on the new [validatejs bridge repository](https://github.com/aurelia/validatejs)

Thanks again!
